us_retail_analysis:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_container
      user: postgres
      password: postgres
      port: 5432
      dbname: retail
      schema: retail
      threads: 1