
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'us_retail'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'us_retail_analysis'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  us_retail:
    sources:
     +materialized: table 
    staging:
     +materialized: view 
    marts:
     +materialized: view 

vars:
  raw_data_tables:
    - name: raw_1992_data
    - name: raw_1993_data
    - name: raw_1994_data
    - name: raw_1995_data
    - name: raw_1996_data
    - name: raw_1997_data
    - name: raw_1998_data
    - name: raw_1999_data
    - name: raw_2000_data
    - name: raw_2001_data
    - name: raw_2002_data
    - name: raw_2003_data
    - name: raw_2004_data
    - name: raw_2005_data
    - name: raw_2006_data
    - name: raw_2007_data
    - name: raw_2008_data
    - name: raw_2009_data
    - name: raw_2010_data
    - name: raw_2011_data
    - name: raw_2012_data
    - name: raw_2013_data
    - name: raw_2014_data
    - name: raw_2015_data
    - name: raw_2016_data
    - name: raw_2017_data
    - name: raw_2018_data
    - name: raw_2019_data
    - name: raw_2020_data
    - name: raw_2021_data
    - name: raw_2022_data
